### ISSUE TITLE
When quick start, package.json is in "docs" directory.

### ISSUE THREAD

**Issue by twtwtw-gj** [vuepress/create-vuepress-site#3]
https://vuepress.vuejs.org/guide/getting-started.html#manual-installation

I read he explanation, and I commanded this in my Windows PC.
```bash 
yarn create vuepress-site twtwtw-gj-site
```
Then, The file twtwtw-gj-site/package.json doesn't exist. 
The file twtwtw-gj-site/docs/package.json exists. And, in docs directory, I commanded `yarn dev` and sacceeded.
It confused me. The main directory should be twtwtw-gj-site.

**Comment by xinpingwang** [comment]
@billyyyyy3320 I created a pull request for this, please review.

**Comment by twtwtw-gj** [comment]
Oh, this issue is duplicated. Not intentionally.
